#!/bin/sh
# finish up the installation
echo "Running postflight script"
umask 022

echo "User is \"$USER\""

PKGROOT="$1/Contents/Resources"
ROOT=$2

# delete any existing installation first

# note: use cp -Rinstead of mv -f to move
# items from /tmp as the user doing the installation

# mv only works if /tmp is owned by the user
# doing the installation

"$PKGROOT/postdelete" "$1"

echo "Moving prefs pane to /Library/PreferencePanes"
cp -R $ROOT/XboxHIDPrefsPane.prefPane /Library/PreferencePanes/

echo "Moving daemon to /Library/PreferencePanes/XboxHIDPrefsPane.prefPane/Contents/Resources"
cp -R $ROOT/XboxHIDDaemonLauncher.app /Library/PreferencePanes/XboxHIDPrefsPane.prefPane/Contents/Resources/


echo "Installing login item"
sudo -u $USER "$PKGROOT/installLoginItem" -install $USER /Library/PreferencePanes/XboxHIDPrefsPane.prefPane/Contents/Resources/XboxHIDDaemonLauncher.app 1

echo "Installing kernel extension"
mv -f $ROOT/DWXboxHIDDriver.kext /System/Library/Extensions


echo "Fix Permissions"
chown -R root:wheel /Library/PreferencePanes/XboxHIDPrefsPane.prefPane
find /Library/PreferencePanes/XboxHIDPrefsPane.prefPane -type d -exec chmod 755 "{}" ";"
find /Library/PreferencePanes/XboxHIDPrefsPane.prefPane -type f -exec chmod 644 "{}" ";"
chmod 755 Library/PreferencePanes/XboxHIDPrefsPane.prefPane/Contents/Resources/XboxHIDDaemonLauncher.app/Contents/MacOS/XboxHIDDaemonLauncher
chmod 755 Library/PreferencePanes/XboxHIDPrefsPane.prefPane/Contents/Resources/XboxHIDDaemonLauncher.app/Contents/Resources/XboxHIDDaemon

chown -R root:wheel /System/Library/Extensions/DWXboxHIDDriver.kext
find /System/Library/Extensions/DWXboxHIDDriver.kext -type d -exec chmod 755 "{}" ";"
find /System/Library/Extensions/DWXboxHIDDriver.kext -type f -exec chmod 644 "{}" ";"
